/**
 * Theme CSS Generator
 *
 * Generates CSS variables from THEME_CSS_VARS in src/config/themes.ts
 * This ensures a single source of truth for theme colors.
 *
 * Run: node scripts/generate-themes.js
 */

const fs = require('fs')
const path = require('path')

// Paths
const themesTsPath = path.join(__dirname, '../src/config/themes.ts')
const outputPath = path.join(__dirname, '../src/themes.generated.css')

/**
 * Extract THEME_CSS_VARS object from themes.ts
 * Simple regex-based extraction to avoid TypeScript parsing complexity
 */
function extractThemeVars(content) {
  // Find the THEME_CSS_VARS export
  const match = content.match(/export const THEME_CSS_VARS\s*=\s*({[\s\S]*?})\s*as const/)
  if (!match) {
    throw new Error('Could not find THEME_CSS_VARS in themes.ts')
  }

  // Parse the object (this is a simplified parser)
  const objString = match[1]

  // Extract theme objects using regex
  const themes = {}
  const themeMatches = objString.matchAll(/(\w+):\s*{([^}]+)}/g)

  for (const match of themeMatches) {
    const themeName = match[1]
    const varsString = match[2]

    // Extract variable names and values
    const vars = {}
    const varMatches = varsString.matchAll(/'([^']+)':\s*'([^']*)'/g)

    for (const varMatch of varMatches) {
      vars[varMatch[1]] = varMatch[2]
    }

    themes[themeName] = vars
  }

  return themes
}

/**
 * Generate CSS from theme variables
 */
function generateCSS(themes) {
  const lines = []

  // Header
  lines.push('/*')
  lines.push(' * Generated by scripts/generate-themes.js')
  lines.push(' * DO NOT EDIT - Modify src/config/themes.ts instead')
  lines.push(' */')
  lines.push('')

  // Helper function to generate CSS variables block
  const generateVarsBlock = (vars, indent = '') => {
    const block = []
    for (const [name, value] of Object.entries(vars)) {
      block.push(`${indent}  ${name}: ${value};`)
    }
    return block.join('\n')
  }

  // Check if all themes have the same variables
  const lightVars = Object.keys(themes.light || {})
  const sepiaVars = Object.keys(themes.sepia || {})
  const darkVars = Object.keys(themes.dark || {})

  // Get all unique variables across all themes
  const allVars = [...new Set([...lightVars, ...sepiaVars, ...darkVars])].sort()

  // Generate :root with light theme as default (or first defined theme)
  const defaultTheme = themes.light || themes.sepia || themes.dark
  if (defaultTheme) {
    lines.push(':root {')
    for (const varName of allVars) {
      if (defaultTheme[varName]) {
        lines.push(`  ${varName}: ${defaultTheme[varName]};`)
      }
    }
    lines.push('}')
    lines.push('')
  }

  // Generate [data-theme="dark"]
  if (themes.dark) {
    lines.push('[data-theme="dark"] {')
    for (const varName of allVars) {
      if (themes.dark[varName]) {
        lines.push(`  ${varName}: ${themes.dark[varName]};`)
      }
    }
    lines.push('}')
    lines.push('')
  }

  // Generate [data-theme="sepia"]
  if (themes.sepia) {
    lines.push('[data-theme="sepia"] {')
    for (const varName of allVars) {
      if (themes.sepia[varName]) {
        lines.push(`  ${varName}: ${themes.sepia[varName]};`)
      }
    }
    lines.push('}')
    lines.push('')
  }

  return lines.join('\n')
}

/**
 * Main execution
 */
function main() {
  console.log('🎨 Generating theme CSS from THEME_CSS_VARS...')

  // Read themes.ts
  if (!fs.existsSync(themesTsPath)) {
    console.error(`❌ Error: ${themesTsPath} not found`)
    process.exit(1)
  }

  const themesContent = fs.readFileSync(themesTsPath, 'utf-8')

  // Extract theme variables
  let themes
  try {
    themes = extractThemeVars(themesContent)
  } catch (error) {
    console.error(`❌ Error extracting theme variables: ${error.message}`)
    process.exit(1)
  }

  // Validate themes
  const requiredThemes = ['light', 'sepia', 'dark']
  for (const themeName of requiredThemes) {
    if (!themes[themeName]) {
      console.error(`❌ Error: Missing required theme "${themeName}"`)
      process.exit(1)
    }
  }

  // Generate CSS
  const css = generateCSS(themes)

  // Write output
  fs.writeFileSync(outputPath, css, 'utf-8')

  console.log(`✅ Generated ${outputPath}`)
  console.log(`   Themes: ${Object.keys(themes).join(', ')}`)
  console.log(`   Variables per theme: ${Object.keys(themes.light).length}`)
}

// Run
main()
